spring:
  rabbitmq:
    host: rabbitmq
  redis:
    host: redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://database:3306/account_service
    username: root
    password: root
    maximum-pool-size: 20
  messages:
    basename: i18n/messages
  jpa:
    hibernate:
      ddl-auto: update
  data:
    cassandra:
      contact-points: cassandra
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: accountEventKeyspace


eureka:
  client:
    healthcheck:
      enabled: true

server:
  use-forward-headers: true