spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://database:3306/account_service
    username: root
    password: root
    maximum-pool-size: 20
  messages:
    basename: i18n/messages
  jpa:
    hibernate:
      ddl-auto: update
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: accountEventKeyspace
  cloud:
    stream:
      bindings:
        accountEventOutboundChannel:
          content-type: application/json

management:
  security:
    enabled: false

security:
  oauth2:
    client:
     clientId: my-trusted-client
     clientSecret:
     accessTokenUri: http://authentication-server:9090/oauth/token
     userAuthorizationUri: http://authentication-server:9090/oauth/authorize
     auto-approve-scopes: '.*'
     registered-redirect-uri: http://authentication-server:9090/login
     clientAuthenticationScheme: form
    resource:
     id: oauth2-resource
     user-info-uri: http://authentication-server:9090/account/userInfo.json

server:
  use-forward-headers: true
  port: 3030

eureka:
  client:
    healthcheck:
      enabled: true