spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account_service
    username: root
    password: root
    maximum-pool-size: 20
  messages:
    basename: i18n/messages
  jpa:
    hibernate:
      ddl-auto: update
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: accountEventKeyspace

server:
  use-forward-headers: true

security:
  oauth2:
    client:
      clientId: my-trusted-client
      clientSecret:
      accessTokenUri: /oauth/access_token
      userAuthorizationUri: /oauth/authorize
      clientAuthenticationScheme: form
    resource:
      filter-order: 3