security:
  rabbitmq:
    host: rabbitmq
  redis:
    host: redis
  security:
    basic:
      enabled: false
    oauth2:
      resource:
       userInfoUri: http://localhost:5050/api/v1/account-service/account/userInfo

spring:
  data:
    cassandra:
      contact-points: cassandra
      keyspace-name: productCatalogEventKeyspace
      schema-action: create_if_not_exists
    mongodb:
      database: product_catalog

server:
  use-forward-headers: true