security:
  basic:
    enabled: false
  oauth2:
    resource:
     userInfoUri: http://localhost:5050/api/v1/account-service/account/userInfo

spring:
  data:
    cassandra:
      keyspace-name: productCatalogEventKeyspace
      schema-action: CREATE_IF_NOT_EXISTS
    mongodb:
      database: product_catalog

server:
  use-forward-headers: true