security:
  basic:
    enabled: false
  oauth2:
     userInfoUri: http://localhost:9090/account/userInfo
     preferTokenInfo: false


spring:
  data:
    cassandra:
      keyspace-name: productCatalogEventKeyspace
      schema-action: CREATE_IF_NOT_EXISTS
    mongodb:
      database: product_catalog

server:
  use-forward-headers: true